// Mock data for Shipments module (frontend-only brainstorming)

export interface Shipment {
  id: string;
  jobNumber: string;
  direction: "export" | "import";
  mode: "ocean" | "air" | "haulage";
  customer: { name: string; tier: number };
  commodity: string;
  weightKg: number;
  origin: { port: string; portCode: string; country: string };
  destination: { port: string; portCode: string; country: string };
  containers: { count: number; size: string };
  carrier: string;
  vessel: string;
  voyage: string;
  etd: string;
  eta: string;
  incoterms: string;
  contractValue: { amount: number; currency: "USD" | "NGN" }[];
  paidPercent: number;
  currentMilestone: string;
  milestoneDetail: string;
  phase: 1 | 2 | 3;
  healthScore: number;
  deadlineStatus: "on-track" | "at-risk" | "breached";
  deadlineLabel: string;
  accountManager: { name: string; initials: string; role: string };
  opsOfficer: { name: string; initials: string; role: string };
  status: "active" | "completed" | "cancelled";
  activatedAt: string;
  daysActive: number;
  totalDays: number;
}

export function formatContractValue(cv: { amount: number; currency: "USD" | "NGN" }[]): string {
  return cv.map(v => v.currency === "USD" ? `$${v.amount.toLocaleString()}` : `₦${v.amount.toLocaleString()}`).join(" + ");
}

export function contractValueUsdEquiv(cv: { amount: number; currency: "USD" | "NGN" }[]): number {
  return cv.reduce((s, v) => s + (v.currency === "USD" ? v.amount : v.amount / 1500), 0);
}

export const mockShipments: Shipment[] = [
  {
    id: "1",
    jobNumber: "ZELOS26050142",
    direction: "export",
    mode: "ocean",
    customer: { name: "Dangote Industries", tier: 1 },
    commodity: "Cement clinker",
    weightKg: 24000,
    origin: { port: "Apapa", portCode: "NGAPP", country: "Nigeria" },
    destination: { port: "Tema", portCode: "GHTEM", country: "Ghana" },
    containers: { count: 6, size: "40HC" },
    carrier: "MSC",
    vessel: "MSC OSCAR",
    voyage: "FN618R",
    etd: "2026-05-26",
    eta: "2026-06-02",
    incoterms: "FOB",
    contractValue: [{ amount: 18500, currency: "USD" }],
    paidPercent: 30,
    currentMilestone: "Gate-in of cargo",
    milestoneDetail: "C02 truck returned — terminal congestion",
    phase: 2,
    healthScore: 32,
    deadlineStatus: "breached",
    deadlineLabel: "−1d 4h",
    accountManager: { name: "Tola Adeyemi", initials: "TA", role: "Sales" },
    opsOfficer: { name: "K. Okafor", initials: "KO", role: "Transport Manager" },
    status: "active",
    activatedAt: "2026-05-20",
    daysActive: 9,
    totalDays: 14,
  },
  {
    id: "2",
    jobNumber: "ZILOS26050089",
    direction: "import",
    mode: "ocean",
    customer: { name: "Flour Mills Nigeria", tier: 1 },
    commodity: "Wheat grain",
    weightKg: 32000,
    origin: { port: "Rotterdam", portCode: "NLRTM", country: "Netherlands" },
    destination: { port: "Apapa", portCode: "NGAPP", country: "Nigeria" },
    containers: { count: 8, size: "20GP" },
    carrier: "Maersk",
    vessel: "MAERSK SELETAR",
    voyage: "MA224W",
    etd: "2026-05-18",
    eta: "2026-06-08",
    incoterms: "CIF",
    contractValue: [{ amount: 22000, currency: "USD" }, { amount: 9600000, currency: "NGN" }],
    paidPercent: 60,
    currentMilestone: "Customs clearance",
    milestoneDetail: "PAAR pending — 2 days overdue",
    phase: 3,
    healthScore: 28,
    deadlineStatus: "breached",
    deadlineLabel: "−2d",
    accountManager: { name: "Tola Adeyemi", initials: "TA", role: "Sales" },
    opsOfficer: { name: "A. Bello", initials: "AB", role: "Clearing Officer" },
    status: "active",
    activatedAt: "2026-05-16",
    daysActive: 13,
    totalDays: 21,
  },
  {
    id: "3",
    jobNumber: "ZELOS26050138",
    direction: "export",
    mode: "ocean",
    customer: { name: "Olam Agri", tier: 2 },
    commodity: "Sesame seeds",
    weightKg: 16000,
    origin: { port: "Apapa", portCode: "NGAPP", country: "Nigeria" },
    destination: { port: "Hamburg", portCode: "DEHAM", country: "Germany" },
    containers: { count: 4, size: "40HC" },
    carrier: "Hapag-Lloyd",
    vessel: "TOKYO EXPRESS",
    voyage: "HL901E",
    etd: "2026-05-24",
    eta: "2026-06-14",
    incoterms: "FOB",
    contractValue: [{ amount: 14200, currency: "USD" }],
    paidPercent: 50,
    currentMilestone: "OBL issuance",
    milestoneDetail: "Freight payment not confirmed",
    phase: 3,
    healthScore: 35,
    deadlineStatus: "breached",
    deadlineLabel: "−8h",
    accountManager: { name: "C. Nwosu", initials: "CN", role: "Sales" },
    opsOfficer: { name: "S. Oluwatuyi", initials: "SO", role: "Ops Manager" },
    status: "active",
    activatedAt: "2026-05-19",
    daysActive: 10,
    totalDays: 16,
  },
  {
    id: "4",
    jobNumber: "ZELOS26050151",
    direction: "export",
    mode: "ocean",
    customer: { name: "BUA Foods", tier: 1 },
    commodity: "Cocoa beans",
    weightKg: 12000,
    origin: { port: "Apapa", portCode: "NGAPP", country: "Nigeria" },
    destination: { port: "Antwerp", portCode: "BEANR", country: "Belgium" },
    containers: { count: 5, size: "40HC" },
    carrier: "MSC",
    vessel: "MSC ELOANE",
    voyage: "FN622R",
    etd: "2026-05-31",
    eta: "2026-06-21",
    incoterms: "FOB",
    contractValue: [{ amount: 8750, currency: "USD" }, { amount: 5250000, currency: "NGN" }],
    paidPercent: 50,
    currentMilestone: "Empty container deployment",
    milestoneDetail: "C03-C05 pending — KAC confirmation",
    phase: 2,
    healthScore: 68,
    deadlineStatus: "at-risk",
    deadlineLabel: "3h 04m",
    accountManager: { name: "Tola Adeyemi", initials: "TA", role: "Sales" },
    opsOfficer: { name: "K. Okafor", initials: "KO", role: "Transport Manager" },
    status: "active",
    activatedAt: "2026-05-23",
    daysActive: 6,
    totalDays: 8,
  },
  {
    id: "5",
    jobNumber: "ZILOS26050094",
    direction: "import",
    mode: "ocean",
    customer: { name: "Lafarge Africa", tier: 1 },
    commodity: "Gypsum",
    weightKg: 22000,
    origin: { port: "Jebel Ali", portCode: "AEJEA", country: "UAE" },
    destination: { port: "Tin Can", portCode: "NGTCN", country: "Nigeria" },
    containers: { count: 4, size: "20GP" },
    carrier: "CMA CGM",
    vessel: "CMA CGM THALASSA",
    voyage: "CC418E",
    etd: "2026-05-20",
    eta: "2026-06-06",
    incoterms: "CIF",
    contractValue: [{ amount: 12000, currency: "USD" }, { amount: 7200000, currency: "NGN" }],
    paidPercent: 40,
    currentMilestone: "Load-out from terminal",
    milestoneDetail: "DO ready — awaiting truck assignment",
    phase: 3,
    healthScore: 62,
    deadlineStatus: "at-risk",
    deadlineLabel: "6h 22m",
    accountManager: { name: "C. Nwosu", initials: "CN", role: "Sales" },
    opsOfficer: { name: "K. Okafor", initials: "KO", role: "Transport Manager" },
    status: "active",
    activatedAt: "2026-05-18",
    daysActive: 11,
    totalDays: 18,
  },
  {
    id: "6",
    jobNumber: "ZELOS26050147",
    direction: "export",
    mode: "ocean",
    customer: { name: "BUA Foods", tier: 1 },
    commodity: "Sugar",
    weightKg: 18000,
    origin: { port: "Apapa", portCode: "NGAPP", country: "Nigeria" },
    destination: { port: "Tema", portCode: "GHTEM", country: "Ghana" },
    containers: { count: 3, size: "40HC" },
    carrier: "MSC",
    vessel: "MSC SHANGHAI",
    voyage: "FN620R",
    etd: "2026-05-30",
    eta: "2026-06-06",
    incoterms: "FOB",
    contractValue: [{ amount: 9800, currency: "USD" }],
    paidPercent: 100,
    currentMilestone: "Vessel confirmation",
    milestoneDetail: "ETD 30 May MSC SHANGHAI",
    phase: 2,
    healthScore: 90,
    deadlineStatus: "on-track",
    deadlineLabel: "2d",
    accountManager: { name: "Tola Adeyemi", initials: "TA", role: "Sales" },
    opsOfficer: { name: "F. Onuoha", initials: "FO", role: "CX Officer" },
    status: "active",
    activatedAt: "2026-05-22",
    daysActive: 7,
    totalDays: 10,
  },
  {
    id: "7",
    jobNumber: "ZILOS26050097",
    direction: "import",
    mode: "air",
    customer: { name: "BUA Foods", tier: 1 },
    commodity: "Industrial flour mill parts",
    weightKg: 2000,
    origin: { port: "Frankfurt", portCode: "FRA", country: "Germany" },
    destination: { port: "Lagos", portCode: "LOS", country: "Nigeria" },
    containers: { count: 1, size: "AWB" },
    carrier: "Lufthansa Cargo",
    vessel: "LH8162",
    voyage: "",
    etd: "2026-05-27",
    eta: "2026-05-29",
    incoterms: "DAP",
    contractValue: [{ amount: 4200, currency: "USD" }],
    paidPercent: 100,
    currentMilestone: "Customs clearance",
    milestoneDetail: "PAAR received — processing",
    phase: 3,
    healthScore: 88,
    deadlineStatus: "on-track",
    deadlineLabel: "1d 4h",
    accountManager: { name: "Tola Adeyemi", initials: "TA", role: "Sales" },
    opsOfficer: { name: "A. Bello", initials: "AB", role: "Clearing Officer" },
    status: "active",
    activatedAt: "2026-05-25",
    daysActive: 4,
    totalDays: 6,
  },
  {
    id: "8",
    jobNumber: "ZELOS26050146",
    direction: "export",
    mode: "ocean",
    customer: { name: "Dufil Prima (Indomie)", tier: 2 },
    commodity: "Instant noodles",
    weightKg: 14000,
    origin: { port: "Apapa", portCode: "NGAPP", country: "Nigeria" },
    destination: { port: "Tema", portCode: "GHTEM", country: "Ghana" },
    containers: { count: 4, size: "20FT" },
    carrier: "PIL",
    vessel: "KOTA PEKARANG",
    voyage: "PL203N",
    etd: "2026-06-02",
    eta: "2026-06-08",
    incoterms: "FOB",
    contractValue: [{ amount: 4600, currency: "USD" }, { amount: 4500000, currency: "NGN" }],
    paidPercent: 0,
    currentMilestone: "Empty deployment",
    milestoneDetail: "4×20FT — depot dispatch today",
    phase: 2,
    healthScore: 85,
    deadlineStatus: "on-track",
    deadlineLabel: "12:00",
    accountManager: { name: "C. Nwosu", initials: "CN", role: "Sales" },
    opsOfficer: { name: "K. Okafor", initials: "KO", role: "Transport Manager" },
    status: "active",
    activatedAt: "2026-05-25",
    daysActive: 4,
    totalDays: 12,
  },
  {
    id: "9",
    jobNumber: "ZELOS26050149",
    direction: "export",
    mode: "ocean",
    customer: { name: "Nestlé Nigeria", tier: 1 },
    commodity: "Processed cocoa",
    weightKg: 8000,
    origin: { port: "Apapa", portCode: "NGAPP", country: "Nigeria" },
    destination: { port: "Antwerp", portCode: "BEANR", country: "Belgium" },
    containers: { count: 2, size: "40RF" },
    carrier: "Maersk",
    vessel: "MAERSK EDMONTON",
    voyage: "MA228E",
    etd: "2026-06-03",
    eta: "2026-06-24",
    incoterms: "CIF",
    contractValue: [{ amount: 11400, currency: "USD" }],
    paidPercent: 25,
    currentMilestone: "Empty deployment",
    milestoneDetail: "2×40RF reefer — pre-cooling required",
    phase: 2,
    healthScore: 82,
    deadlineStatus: "on-track",
    deadlineLabel: "16:00",
    accountManager: { name: "Tola Adeyemi", initials: "TA", role: "Sales" },
    opsOfficer: { name: "K. Okafor", initials: "KO", role: "Transport Manager" },
    status: "active",
    activatedAt: "2026-05-26",
    daysActive: 3,
    totalDays: 10,
  },
  {
    id: "10",
    jobNumber: "ZELOS26050152",
    direction: "export",
    mode: "ocean",
    customer: { name: "Friesland Campina", tier: 2 },
    commodity: "Evaporated milk",
    weightKg: 6000,
    origin: { port: "Tin Can", portCode: "NGTCN", country: "Nigeria" },
    destination: { port: "Mombasa", portCode: "KEMBA", country: "Kenya" },
    containers: { count: 1, size: "40RF" },
    carrier: "MSC",
    vessel: "MSC RAVENNA",
    voyage: "FN625R",
    etd: "2026-06-05",
    eta: "2026-06-22",
    incoterms: "FOB",
    contractValue: [{ amount: 5200, currency: "USD" }],
    paidPercent: 0,
    currentMilestone: "Identify transporter",
    milestoneDetail: "40RF deployment — vendor selection",
    phase: 2,
    healthScore: 78,
    deadlineStatus: "on-track",
    deadlineLabel: "EoD",
    accountManager: { name: "C. Nwosu", initials: "CN", role: "Sales" },
    opsOfficer: { name: "F. Onuoha", initials: "FO", role: "CX Officer" },
    status: "active",
    activatedAt: "2026-05-27",
    daysActive: 2,
    totalDays: 14,
  },
];

// Completed shipments for reference
export const completedShipments: Shipment[] = [
  {
    id: "c1",
    jobNumber: "ZELOS26050128",
    direction: "export",
    mode: "ocean",
    customer: { name: "Olam Agri", tier: 2 },
    commodity: "Cocoa beans",
    weightKg: 16000,
    origin: { port: "Apapa", portCode: "NGAPP", country: "Nigeria" },
    destination: { port: "Antwerp", portCode: "BEANR", country: "Belgium" },
    containers: { count: 4, size: "40HC" },
    carrier: "MSC",
    vessel: "MSC TRIESTE",
    voyage: "FN610R",
    etd: "2026-05-12",
    eta: "2026-06-01",
    incoterms: "FOB",
    contractValue: [{ amount: 13800, currency: "USD" }],
    paidPercent: 100,
    currentMilestone: "Completed",
    milestoneDetail: "Closed 18 May — 7 day cycle",
    phase: 3,
    healthScore: 100,
    deadlineStatus: "on-track",
    deadlineLabel: "Closed",
    accountManager: { name: "Tola Adeyemi", initials: "TA", role: "Sales" },
    opsOfficer: { name: "K. Okafor", initials: "KO", role: "Transport Manager" },
    status: "completed",
    activatedAt: "2026-05-11",
    daysActive: 7,
    totalDays: 7,
  },
];
