import { Router } from "express";
import { healthRouter } from "./health";
import { companiesRouter } from "./companies";
import { contactsRouter } from "./contacts";
import { rfqsRouter } from "./rfqs";
import { quotesRouter } from "./quotes";
import { ratesRouter } from "./rates";
import { partnersRouter } from "./partners";
import { settingsRouter } from "./settings";
import { seedRouter } from "./seed";
import { gmailRouter } from "./gmail";
import { emailAccountsRouter } from "./email-accounts";
import { microsoftAuthRouter } from "./microsoft-auth";
import { googleAuthRouter } from "./google-auth";
import { emailSyncRouter } from "./email-sync";
import { brainRouter } from "./brain";
import { usersRouter } from "./users";
import { opportunitiesRouter } from "./opportunities";
import { activitiesRouter } from "./activities";
import { marketRouter } from "./market";

const router = Router();

router.use(healthRouter);
router.use(companiesRouter);
router.use(contactsRouter);
router.use(rfqsRouter);
router.use(quotesRouter);
router.use(ratesRouter);
router.use(partnersRouter);
router.use(settingsRouter);
router.use(seedRouter);
router.use(gmailRouter);
router.use(emailAccountsRouter);
router.use(microsoftAuthRouter);
router.use(googleAuthRouter);
router.use(emailSyncRouter);
router.use(brainRouter);
router.use(usersRouter);
router.use(opportunitiesRouter);
router.use(activitiesRouter);
router.use(marketRouter);

export default router;
